# conda env create -f environment.yml
name: pymars
channels:
    - anaconda
    - conda-forge
    - menpo
dependencies:
    - astropy
    - python >= 3.6
    - jupyter
    - matplotlib
    - numpy >= 1.15.0
    - scipy
    - pandas
    - scikit-learn
    - pip
    - uproot
    - pytables
    - pip:
        - ctaplot >= 0.5.6
